# Generated by Django 4.1.10 on 2023-08-15 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=12)),
                ('title', models.TextField()),
                ('abstract', models.TextField()),
                ('fl_subject', models.TextField()),
                ('sl_subject', models.TextField()),
            ],
        ),
    ]
